In [51]:
import json
from fastf1.ergast import Ergast

ergast = Ergast(result_type='pandas')

with open("season_info.json") as file:
    season_info = json.loads(file.read())
races_2024 = season_info["races"]
drivers = season_info["drivers"]

In [66]:
number_of_races = 1

for i in range(number_of_races): 
    i += 1
    pit_stops = ergast.get_pit_stops(season=2024, round=i)

    data = pit_stops.content[0]

    data["driverId"] = data["driverId"].str.title()

    data["driverId"] = data["driverId"].str.split("_")
    data["driverId"] = data["driverId"].str[-1]

In [64]:
data

      driverId  stop  lap      time               duration
0   Hulkenberg     1    1  18:05:33 0 days 00:00:36.604000
1         Zhou     1    9  18:18:39 0 days 00:00:25.208000
2       Stroll     1    9  18:18:42 0 days 00:00:24.418000
3         Ocon     1   10  18:20:20 0 days 00:00:24.877000
4     Sargeant     1   10  18:21:19 0 days 00:00:35.729000
5      Russell     1   11  18:21:38 0 days 00:00:24.778000
6      Leclerc     1   11  18:21:41 0 days 00:00:24.069000
7    Magnussen     1   11  18:21:55 0 days 00:00:25.951000
8        Perez     1   12  18:23:16 0 days 00:00:24.516000
9      Piastri     1   12  18:23:24 0 days 00:00:25.450000
10    Hamilton     1   12  18:23:26 0 days 00:00:25.087000
11       Gasly     1   12  18:23:38 0 days 00:00:29.980000
12      Bottas     1   12  18:23:42 0 days 00:00:26.420000
13      Norris     1   13  18:25:00 0 days 00:00:24.205000
14   Ricciardo     1   13  18:25:17 0 days 00:00:24.988000
15       Sainz     1   14  18:26:32 0 days 00:00:24.474000
16     Tsunoda     1   14  18:26:47 0 days 00:00:24.724000
17      Alonso     1   15  18:28:24 0 days 00:00:24.786000
18       Albon     1   15  18:28:29 0 days 00:00:24.681000
19  Verstappen     1   17  18:31:12 0 days 00:00:25.064000
20  Hulkenberg     2   20  18:37:08 0 days 00:00:24.768000
21      Stroll     2   27  18:48:25 0 days 00:00:24.545000
22        Zhou     2   28  18:49:59 0 days 00:00:25.094000
23    Sargeant     2   28  18:51:33 0 days 00:00:25.070000
24        Ocon     2   30  18:53:30 0 days 00:00:25.145000
25      Bottas     2   30  18:53:32 0 days 00:01:14.773000
26     Russell     2   31  18:54:21 0 days 00:00:24.866000
27       Gasly     2   31  18:55:10 0 days 00:00:26.462000
28   Magnussen     2   32  18:56:37 0 days 00:00:24.446000
29      Norris     2   33  18:57:39 0 days 00:00:24.705000